<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita88d269bcc755c7d43c0e0e36f5200d1
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Mention\\Plugin\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Mention\\Plugin\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita88d269bcc755c7d43c0e0e36f5200d1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita88d269bcc755c7d43c0e0e36f5200d1::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita88d269bcc755c7d43c0e0e36f5200d1::$classMap;

        }, null, ClassLoader::class);
    }
}
